# These are supported funding model platforms

github: prajwalkoirala23
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: prajwalkoirala23
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: prajwalkoirala23
issuehunt: livechief
otechie: # Replace with a single Otechie username (BETA)
custom: paypal.me/prajwalkoirala23
custom: https://commerce.coinbase.com/checkout/7f2c01ea-e513-4591-a3e2-c107770b1860
